parameters:
  source: docs
  output: docs/book
  remote: origin
  ref: refs/heads/master
  branch: 'gh-pages'
  preSteps: []
  beforePublishSteps: []
  postSteps: []

jobs:

- job: docs
  pool:
    vmImage: ubuntu-latest
  condition: eq(variables['Build.SourceBranch'], '${{ parameters.ref }}')
  steps:
  - checkout: self
    persistCredentials: true
  - ${{ parameters.preSteps }}
  - script: |
      git config --local user.name "Azure Pipelines"
      git config --local user.email "azuredevops@microsoft.com"
    displayName: Configure git
  - template: ../steps/install-mdbook.yml
  - script: |
      mdbook build
    displayName: mdBook build
    workingDirectory: $(Build.SourcesDirectory)/${{ parameters.source }}
  - ${{ parameters.beforePublishSteps }}
  - script: |
      git add -f ${{ parameters.output }}
      git commit -m "Deploy docs for $(Build.SourceVersion)"
      git subtree split --prefix ${{ parameters.output }} -b ${{ parameters.branch }}
      git push -f ${{ parameters.remote }} ${{ parameters.branch }}:${{ parameters.branch }}
    workingDirectory: $(Build.SourcesDirectory)
    displayName: GitHub Pages
  - ${{ parameters.postSteps }}
