parameters:
  name: 'vhdeps'
  version: latest
  sources: ['.']
  args: []
  preSteps: []
  postSteps: []

jobs:

- job: ${{ parameters.name }}
  pool:
    vmImage: ubuntu-latest
  container: abstudelft/vhdeps:${{ parameters.version }}
  steps:
  - ${{ parameters.preSteps }}
  - task: UseDotNet@2
    inputs:
      version: 2.x
  - script: |
      vhdeps -i ${{ join(' -i', parameters.sources) }} ghdl -- ${{ join(' ', parameters.args) }} -c xml -d .
    displayName: vhdeps
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
  - script: |
      bash <(curl https://codecov.io/bash) -f coverage.xml
    env:
      CODECOV_TOKEN: $(codecov)
    displayName: codecov
  - ${{ parameters.postSteps }}
